DROP DATABASE IF EXISTS BullsAndCowsDBTest;
CREATE DATABASE BullsAndCowsDBTest;

USE BullsAndCowsDBTest;

CREATE TABLE Game (
gameId INT PRIMARY KEY AUTO_INCREMENT,
answer CHAR(4) NOT NULL,
finished BIT NOT NULL
);

CREATE TABLE Round (
roundId INT PRIMARY KEY AUTO_INCREMENT,
gameId INT NOT NULL,
guess CHAR(4) NOT NULL,
`timeStamp` DATETIME NOT NULL,
result VARCHAR(10) NOT NULL,
FOREIGN KEY(gameId) REFERENCES Game(gameId)
);
