DROP DATABASE IF EXISTS BullsAndCows;
CREATE DATABASE BullsAndCows;

USE BullsAndCows;

CREATE TABLE Game (
gameId INT PRIMARY KEY AUTO_INCREMENT,
answer CHAR(4) NOT NULL,
finished BIT NOT NULL
);

CREATE TABLE Round (
roundId INT PRIMARY KEY AUTO_INCREMENT,
gameId INT,
guess CHAR(4) NOT NULL,
`timeStamp` DATE NOT NULL,
result VARCHAR(10) NOT NULL,
FOREIGN KEY(gameId) REFERENCES Game(gameId)
);